BoxLayout:
    orientation: 'vertical'

    MDLabel:
        text: 'Test Label'
        halign: 'center'
        size_hint_y: 0.1
        theme_text_color: 'Primary'

    MDTextField:
        id: test_input
        hint_text: 'Type something here'
        size_hint_y: 0.1
        multiline: False
        mode: 'rectangle'

    MDRaisedButton:
        text: 'Submit'
        size_hint_y: 0.1
        pos_hint: {"center_x": .5}
